### ISSUE TITLE
Is this a typo?

### ISSUE THREAD

**Issue by projectoriented** [EichlerLab/svpop#11]
Hi Peter 👋 !

Is this reference a typo? I don't see `bed_filt` in the `input` declaration.
https://github.com/EichlerLab/svpop/blob/ea970f30fdf3bce07740ddcf9477011e1edecba9/rules/variant/variant_global.snakefile#L84

**Comment by projectoriented** [comment]
And within this function, is it necessary for [`input_format`](https://github.com/EichlerLab/svpop/blob/ea970f30fdf3bce07740ddcf9477011e1edecba9/svpoplib/seq.py#L97) and [`fa_file_name`](https://github.com/EichlerLab/svpop/blob/ea970f30fdf3bce07740ddcf9477011e1edecba9/svpoplib/seq.py#L98C13-L98C25) to be defined before calling?: 

https://github.com/EichlerLab/svpop/blob/ea970f30fdf3bce07740ddcf9477011e1edecba9/svpoplib/seq.py#L13C5-L13C26

**Comment by paudano** [comment]
The first error in variant_global was fixed in a previous version. I'm pushing a fix for the second issue soon.
