### ISSUE TITLE
Missing or 0-length SVLEN and no END for symbolic SV

### ISSUE THREAD

**Issue by Zoeyoungxy** [EichlerLab/svpop#12]
Hi,
I used svpop to merge the results of hificnv, the file looks like:
##FILTER=<ID=TARGET_SIZE,Description="Call is smaller than the target size of 100kbp"
##INFO=<ID=CIPOS,Number=2,Type=Integer,Description="Confidence interval around POS"
##INFO=<ID=CIEND,Number=2,Type=Integer,Description="Confidence interval around END"
##INFO=<ID=END,Number=1,Type=Integer,Description="End position of the structural variant"
##INFO=<ID=IMPRECISE,Number=0,Type=Flag,Description="Imprecise structural variation"
##INFO=<ID=SVLEN,Number=1,Type=Integer,Description="Length of the SV"
##INFO=<ID=SVTYPE,Number=1,Type=String,Description="Type of the SV."
##ALT=<ID=DEL,Description="Deletion"
##ALT=<ID=DUP,Description="Duplication"
##FORMAT=<ID=CN,Number=1,Type=Float,Description="Copy number genotype for imprecise events"
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype"
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  SS0105-L
chr1    350001  .       N       <DEL>   83      PASS    IMPRECISE;SVTYPE=DEL;END=496000;SVLEN=146000;CIPOS=-2000,2000;CIEND=-2000,2000  GT:CN   0/1:1
chr1    2394001 .       N       <DEL>   69      PASS    IMPRECISE;SVTYPE=DEL;END=2658000;SVLEN=264000;CIPOS=-2000,2000;CIEND=-2000,2000 GT:CN   0/1:1
chr1    13118001        .       N       <DEL>   63      PASS    IMPRECISE;SVTYPE=DEL;END=13306000;SVLEN=188000;CIPOS=-2000,2000;CIEND=-2000,2000        GT:CN   0/1:1
chr1    121662001       .       N       <DEL>   57      PASS    
IMPRECISE;SVTYPE=DEL;END=121910000;SVLEN=248000;CIPOS=-2000,2000;CIEND=-2000,2000       GT:CN   0/1:1

Since HiFiCNV is not included in the supported types, I chose "vcf" as "TYPE" needed in samples.tsv.
However, I met the error message `Missing or 0-length SVLEN and no END for symbolic SV: Row 0`
I checked the script and found the raise RuntimeError in svpoplib/variant.py:
<img width="671" alt="image" src="https://github.com/EichlerLab/svpop/assets/128593066/13f59a03-b67a-4930-af0d-635a59afe0c2">
Both "END" and "SVLEN" are contained in the 'INFO' column. Why I got this error message? Can you give me some information on how to merge the results of HiFiCNV?
Thanks!

Best,
Zoey

**Comment by paudano** [comment]
For "vcf", you have to tell it which fields to pull. If you add a "CONFIG" column to `config/samples.tsv` (or whatever `variant_table` points to in `config.json`), then you can tell it which fields to pull from the VCF.

In `README.md`, there's some guidance for including fields from INFO and FORMAT.
```
vcf: DATA is a path to an arbitrary VCF.
    * Use PARAM field keywords "info" and "format" to specify INFO and FORMAT fields to include in the BED file as
     variant annotations (e.g. "info=AF;format=GT,GQ").
```

For HiFiCNV, I think "info=END,SVLEN,SVTYPE;format=GT" should work.

I'll add a hificnv preset once I have a moment to implement and test it. Let me know if this works for you.

**Comment by Zoeyoungxy** [comment]
> For "vcf", you have to tell it which fields to pull. If you add a "CONFIG" column to `config/samples.tsv` (or whatever `variant_table` points to in `config.json`), then you can tell it which fields to pull from the VCF.
> 
> In `README.md`, there's some guidance for including fields from INFO and FORMAT.
> 
> ```
> vcf: DATA is a path to an arbitrary VCF.
>     * Use PARAM field keywords "info" and "format" to specify INFO and FORMAT fields to include in the BED file as
>      variant annotations (e.g. "info=AF;format=GT,GQ").
> ```
> 
> For HiFiCNV, I think "info=END,SVLEN,SVTYPE;format=GT" should work.
> 
> I'll add a hificnv preset once I have a moment to implement and test it. Let me know if this works for you.

This really works for me. Thank You!
