### ISSUE TITLE
single positional indexer is out-of-bounds

### ISSUE THREAD

**Issue by zou-yawen** [EichlerLab/svpop#3]
hi, I meet a problem and try many ways to solve it , it still can  not work.Could you please help me to figure out.The error is below:
![image](https://user-images.githubusercontent.com/72124697/183277492-85a7c52a-89ea-4c19-aec9-ec650c282eff.png)

**Comment by paudano** [comment]
I completely lost this issues, my appologies. If you still have problems, please let me know. It's an old issues, so I assume you solved it or moved on, but I'll watch my github issues closer for this project.
