### ISSUE TITLE
How to interpret the TRF fields?

### ISSUE THREAD

**Issue by projectoriented** [EichlerLab/svpop#5]
Hello 👋 !

Thanks for developing this.

Can you please briefly explain how I interpret these fields?
`REF_TRF TRF_COPIES      TRF_PFCT_N      TRF_PFCT_BP     TRF_PROP`

Thanks!

**Comment by paudano** [comment]
REF_TRF and TRF_COPIES come directly from trf, and they are the consensus and number of copies. TRF_PFCT_N and TRF_PFCT_BP are the number and total size of perfect repeats with no SNPs and indels. TRF_PROP tells you the proportion of the variant call the repeat covers in the range (0.0 to 1.0] (0.0 = 0%, 1.0 = 100%).
