### ISSUE TITLE
Sniffles2 symbolic alleles

### ISSUE THREAD

**Issue by juniper-lake** [EichlerLab/svpop#6]
Handling of symbolic variants in `vcf_fields_to_seq()` of [svpoplib/variant.py](https://github.com/EichlerLab/svpop/blob/c36d6ed500c4bec5ed21d2e2d8fc20ecc8641e51/svpoplib/variant.py#L342) prevents Sniffles INS/DEL from merging. 

The problem is Sniffles2 produces a sprinkling of symbolic alleles for SVTYPE=INS and SVTYPE=DEL with no provided sequence, which means seq=np.nan, triggering [this RuntimeError in svmerge.py](https://github.com/EichlerLab/svpop/blob/c36d6ed500c4bec5ed21d2e2d8fc20ecc8641e51/svpoplib/svmerge.py#L822) because sequence matching can't occur. 

My quick fix was to classify symbolic INS/DEL with no SEQ as an unused SVTYPE called "PSEUDO_SYM" so they don't affect INS/DEL merges but I'm sure there's a better method.

**Comment by juniper-lake** [comment]
An example vcf entry:

```
chr20   28889474        Sniffles2.INS.19DS13    N       <INS>   53      GT      IMPRECISE;SVTYPE=INS;SVLEN=170;END=28889474;SUPPORT=2;COVERAGE=7,18,17,19,15;STRAND=+-;AF=0.118;STDEV_LEN=14.142;STDEV_POS=25.456;SUPPORT_LONG=0        GT:GQ:DR:DV     0/0:21:15:2
```

**Comment by paudano** [comment]
Addressing with #7.
