### ISSUE TITLE
CCRE does not evaluate score

### ISSUE THREAD

**Issue by wharvey31** [EichlerLab/svpop#9]
Hello,

The following pattern does not seem like it works with a score. It works with `all` but not `100`. Can you confirm? Or is there a different range to operate on? If so, can you implement a check for the score metric that fails if a score is not valid?

`results/variant/caller/{sourcename}/{sample}/{filter}/all/anno/ccre/ccre2020-{score}_{vartype}_{svtype}.tsv.gz`

Thanks!

**Comment by paudano** [comment]
It just works with "all" for now. I may update this later, but with hs1 now out and annotations done differently through it, I'm not sure if I can keep up with all the changes in SV-Pop.
